//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatVision.Wpf.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatVision.Wpf.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddinPara 的本地化字符串。
        /// </summary>
        internal static string AddinPara {
            get {
                return ResourceManager.GetString("AddinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm 的本地化字符串。
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlgorithmScript 的本地化字符串。
        /// </summary>
        internal static string AlgorithmScript {
            get {
                return ResourceManager.GetString("AlgorithmScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BaudRate 的本地化字符串。
        /// </summary>
        internal static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera 的本地化字符串。
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraAddinPara 的本地化字符串。
        /// </summary>
        internal static string CameraAddinPara {
            get {
                return ResourceManager.GetString("CameraAddinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraList 的本地化字符串。
        /// </summary>
        internal static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraName 的本地化字符串。
        /// </summary>
        internal static string CameraName {
            get {
                return ResourceManager.GetString("CameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraProvider 的本地化字符串。
        /// </summary>
        internal static string CameraProvider {
            get {
                return ResourceManager.GetString("CameraProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraSet 的本地化字符串。
        /// </summary>
        internal static string CameraSet {
            get {
                return ResourceManager.GetString("CameraSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraSN 的本地化字符串。
        /// </summary>
        internal static string CameraSN {
            get {
                return ResourceManager.GetString("CameraSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearAlarm 的本地化字符串。
        /// </summary>
        internal static string ClearAlarm {
            get {
                return ResourceManager.GetString("ClearAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommunicationSet 的本地化字符串。
        /// </summary>
        internal static string CommunicationSet {
            get {
                return ResourceManager.GetString("CommunicationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile 的本地化字符串。
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfirmReset 的本地化字符串。
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continuous 的本地化字符串。
        /// </summary>
        internal static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CpuType 的本地化字符串。
        /// </summary>
        internal static string CpuType {
            get {
                return ResourceManager.GetString("CpuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentFile 的本地化字符串。
        /// </summary>
        internal static string CurrentFile {
            get {
                return ResourceManager.GetString("CurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentSolution 的本地化字符串。
        /// </summary>
        internal static string CurrentSolution {
            get {
                return ResourceManager.GetString("CurrentSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentUser 的本地化字符串。
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataBits 的本地化字符串。
        /// </summary>
        internal static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserialize 的本地化字符串。
        /// </summary>
        internal static string Deserialize {
            get {
                return ResourceManager.GetString("Deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer 的本地化字符串。
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceAlarm 的本地化字符串。
        /// </summary>
        internal static string DeviceAlarm {
            get {
                return ResourceManager.GetString("DeviceAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceList 的本地化字符串。
        /// </summary>
        internal static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam 的本地化字符串。
        /// </summary>
        internal static string DeviceParam {
            get {
                return ResourceManager.GetString("DeviceParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_AutoOpenCamera 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_AutoOpenCamera {
            get {
                return ResourceManager.GetString("DeviceParam_AutoOpenCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_Camera 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_Camera {
            get {
                return ResourceManager.GetString("DeviceParam_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_DeviceParam 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_DeviceParam {
            get {
                return ResourceManager.GetString("DeviceParam_DeviceParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_Else 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_Else {
            get {
                return ResourceManager.GetString("DeviceParam_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_GeneralParam 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_GeneralParam {
            get {
                return ResourceManager.GetString("DeviceParam_GeneralParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_new RoutedCommandRecipe 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_new_RoutedCommandRecipe {
            get {
                return ResourceManager.GetString("DeviceParam_new RoutedCommandRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_Path 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_Path {
            get {
                return ResourceManager.GetString("DeviceParam_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_ProcessParam 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_ProcessParam {
            get {
                return ResourceManager.GetString("DeviceParam_ProcessParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_Recipe 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_Recipe {
            get {
                return ResourceManager.GetString("DeviceParam_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_SaveManufactureResult 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_SaveManufactureResult {
            get {
                return ResourceManager.GetString("DeviceParam_SaveManufactureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceParam_UseCamera 的本地化字符串。
        /// </summary>
        internal static string DeviceParam_UseCamera {
            get {
                return ResourceManager.GetString("DeviceParam_UseCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary 的本地化字符串。
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconntect 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Curve 的本地化字符串。
        /// </summary>
        internal static string Dock_Curve {
            get {
                return ResourceManager.GetString("Dock_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Data 的本地化字符串。
        /// </summary>
        internal static string Dock_Data {
            get {
                return ResourceManager.GetString("Dock_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_DeviceState 的本地化字符串。
        /// </summary>
        internal static string Dock_DeviceState {
            get {
                return ResourceManager.GetString("Dock_DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Load 的本地化字符串。
        /// </summary>
        internal static string Dock_Load {
            get {
                return ResourceManager.GetString("Dock_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Log 的本地化字符串。
        /// </summary>
        internal static string Dock_Log {
            get {
                return ResourceManager.GetString("Dock_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_ManufactureParam 的本地化字符串。
        /// </summary>
        internal static string Dock_ManufactureParam {
            get {
                return ResourceManager.GetString("Dock_ManufactureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_ModuleOut 的本地化字符串。
        /// </summary>
        internal static string Dock_ModuleOut {
            get {
                return ResourceManager.GetString("Dock_ModuleOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Process 的本地化字符串。
        /// </summary>
        internal static string Dock_Process {
            get {
                return ResourceManager.GetString("Dock_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_ProductionInfo 的本地化字符串。
        /// </summary>
        internal static string Dock_ProductionInfo {
            get {
                return ResourceManager.GetString("Dock_ProductionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Reset 的本地化字符串。
        /// </summary>
        internal static string Dock_Reset {
            get {
                return ResourceManager.GetString("Dock_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Save 的本地化字符串。
        /// </summary>
        internal static string Dock_Save {
            get {
                return ResourceManager.GetString("Dock_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_TemplateObject 的本地化字符串。
        /// </summary>
        internal static string Dock_TemplateObject {
            get {
                return ResourceManager.GetString("Dock_TemplateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Tool 的本地化字符串。
        /// </summary>
        internal static string Dock_Tool {
            get {
                return ResourceManager.GetString("Dock_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock_Vision 的本地化字符串。
        /// </summary>
        internal static string Dock_Vision {
            get {
                return ResourceManager.GetString("Dock_Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emergency 的本地化字符串。
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpoTime 的本地化字符串。
        /// </summary>
        internal static string ExpoTime {
            get {
                return ResourceManager.GetString("ExpoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinishSignal 的本地化字符串。
        /// </summary>
        internal static string FinishSignal {
            get {
                return ResourceManager.GetString("FinishSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gain 的本地化字符串。
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GlobalVar 的本地化字符串。
        /// </summary>
        internal static string GlobalVar {
            get {
                return ResourceManager.GetString("GlobalVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HardwareConfig 的本地化字符串。
        /// </summary>
        internal static string HardwareConfig {
            get {
                return ResourceManager.GetString("HardwareConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HelpDecomentNotFind 的本地化字符串。
        /// </summary>
        internal static string HelpDecomentNotFind {
            get {
                return ResourceManager.GetString("HelpDecomentNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InputStart 的本地化字符串。
        /// </summary>
        internal static string InputStart {
            get {
                return ResourceManager.GetString("InputStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO 的本地化字符串。
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOParam 的本地化字符串。
        /// </summary>
        internal static string IOParam {
            get {
                return ResourceManager.GetString("IOParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ip 的本地化字符串。
        /// </summary>
        internal static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LampGreen 的本地化字符串。
        /// </summary>
        internal static string LampGreen {
            get {
                return ResourceManager.GetString("LampGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LampRed 的本地化字符串。
        /// </summary>
        internal static string LampRed {
            get {
                return ResourceManager.GetString("LampRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LampYellow 的本地化字符串。
        /// </summary>
        internal static string LampYellow {
            get {
                return ResourceManager.GetString("LampYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadProject 的本地化字符串。
        /// </summary>
        internal static string LoadProject {
            get {
                return ResourceManager.GetString("LoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogDock 的本地化字符串。
        /// </summary>
        internal static string LogDock {
            get {
                return ResourceManager.GetString("LogDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_Account 的本地化字符串。
        /// </summary>
        internal static string Login_Account {
            get {
                return ResourceManager.GetString("Login_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_ChangePwd 的本地化字符串。
        /// </summary>
        internal static string Login_ChangePwd {
            get {
                return ResourceManager.GetString("Login_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_Login 的本地化字符串。
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_Logout 的本地化字符串。
        /// </summary>
        internal static string Login_Logout {
            get {
                return ResourceManager.GetString("Login_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_Password 的本地化字符串。
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login_UserLogin 的本地化字符串。
        /// </summary>
        internal static string Login_UserLogin {
            get {
                return ResourceManager.GetString("Login_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogView_Bottom 的本地化字符串。
        /// </summary>
        internal static string LogView_Bottom {
            get {
                return ResourceManager.GetString("LogView_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogView_Content 的本地化字符串。
        /// </summary>
        internal static string LogView_Content {
            get {
                return ResourceManager.GetString("LogView_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogView_Time 的本地化字符串。
        /// </summary>
        internal static string LogView_Time {
            get {
                return ResourceManager.GetString("LogView_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogView_Top 的本地化字符串。
        /// </summary>
        internal static string LogView_Top {
            get {
                return ResourceManager.GetString("LogView_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogView_Type 的本地化字符串。
        /// </summary>
        internal static string LogView_Type {
            get {
                return ResourceManager.GetString("LogView_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainView 的本地化字符串。
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_About 的本地化字符串。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Camera 的本地化字符串。
        /// </summary>
        internal static string Menu_Camera {
            get {
                return ResourceManager.GetString("Menu_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Curve 的本地化字符串。
        /// </summary>
        internal static string Menu_Curve {
            get {
                return ResourceManager.GetString("Menu_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_DeviceParam 的本地化字符串。
        /// </summary>
        internal static string Menu_DeviceParam {
            get {
                return ResourceManager.GetString("Menu_DeviceParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Edit 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Help 的本地化字符串。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_HelpDocument 的本地化字符串。
        /// </summary>
        internal static string Menu_HelpDocument {
            get {
                return ResourceManager.GetString("Menu_HelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_License 的本地化字符串。
        /// </summary>
        internal static string Menu_License {
            get {
                return ResourceManager.GetString("Menu_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_LoadDefaultLayout 的本地化字符串。
        /// </summary>
        internal static string Menu_LoadDefaultLayout {
            get {
                return ResourceManager.GetString("Menu_LoadDefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_LoadLayout 的本地化字符串。
        /// </summary>
        internal static string Menu_LoadLayout {
            get {
                return ResourceManager.GetString("Menu_LoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Log 的本地化字符串。
        /// </summary>
        internal static string Menu_Log {
            get {
                return ResourceManager.GetString("Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_ManufatureParam 的本地化字符串。
        /// </summary>
        internal static string Menu_ManufatureParam {
            get {
                return ResourceManager.GetString("Menu_ManufatureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Open 的本地化字符串。
        /// </summary>
        internal static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_OpenFile 的本地化字符串。
        /// </summary>
        internal static string Menu_OpenFile {
            get {
                return ResourceManager.GetString("Menu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Param 的本地化字符串。
        /// </summary>
        internal static string Menu_Param {
            get {
                return ResourceManager.GetString("Menu_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_ProductionInfo 的本地化字符串。
        /// </summary>
        internal static string Menu_ProductionInfo {
            get {
                return ResourceManager.GetString("Menu_ProductionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_ReportQuery 的本地化字符串。
        /// </summary>
        internal static string Menu_ReportQuery {
            get {
                return ResourceManager.GetString("Menu_ReportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Save 的本地化字符串。
        /// </summary>
        internal static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_SaveFile 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveFile {
            get {
                return ResourceManager.GetString("Menu_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_SaveLayout 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveLayout {
            get {
                return ResourceManager.GetString("Menu_SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_ScreenCapture 的本地化字符串。
        /// </summary>
        internal static string Menu_ScreenCapture {
            get {
                return ResourceManager.GetString("Menu_ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_SystemConfig 的本地化字符串。
        /// </summary>
        internal static string Menu_SystemConfig {
            get {
                return ResourceManager.GetString("Menu_SystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_SystemParam 的本地化字符串。
        /// </summary>
        internal static string Menu_SystemParam {
            get {
                return ResourceManager.GetString("Menu_SystemParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_TemplateObject 的本地化字符串。
        /// </summary>
        internal static string Menu_TemplateObject {
            get {
                return ResourceManager.GetString("Menu_TemplateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_Tools 的本地化字符串。
        /// </summary>
        internal static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_UserFeedback 的本地化字符串。
        /// </summary>
        internal static string Menu_UserFeedback {
            get {
                return ResourceManager.GetString("Menu_UserFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu_View 的本地化字符串。
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MotionSet 的本地化字符串。
        /// </summary>
        internal static string MotionSet {
            get {
                return ResourceManager.GetString("MotionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewSolution 的本地化字符串。
        /// </summary>
        internal static string NewSolution {
            get {
                return ResourceManager.GetString("NewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NullImage 的本地化字符串。
        /// </summary>
        internal static string NullImage {
            get {
                return ResourceManager.GetString("NullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NullTypeOrMethod 的本地化字符串。
        /// </summary>
        internal static string NullTypeOrMethod {
            get {
                return ResourceManager.GetString("NullTypeOrMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ObjectName 的本地化字符串。
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFile 的本地化字符串。
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenImage 的本地化字符串。
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate 的本地化字符串。
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OperatorLoginSystem 的本地化字符串。
        /// </summary>
        internal static string OperatorLoginSystem {
            get {
                return ResourceManager.GetString("OperatorLoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutputFinish 的本地化字符串。
        /// </summary>
        internal static string OutputFinish {
            get {
                return ResourceManager.GetString("OutputFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter_Setting 的本地化字符串。
        /// </summary>
        internal static string Parameter_Setting {
            get {
                return ResourceManager.GetString("Parameter_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ParaSetting 的本地化字符串。
        /// </summary>
        internal static string ParaSetting {
            get {
                return ResourceManager.GetString("ParaSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity 的本地化字符串。
        /// </summary>
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC_Ready 的本地化字符串。
        /// </summary>
        internal static string PC_Ready {
            get {
                return ResourceManager.GetString("PC_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PleaseLoginFirst 的本地化字符串。
        /// </summary>
        internal static string PleaseLoginFirst {
            get {
                return ResourceManager.GetString("PleaseLoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power 的本地化字符串。
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerDownLimit 的本地化字符串。
        /// </summary>
        internal static string PowerDownLimit {
            get {
                return ResourceManager.GetString("PowerDownLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerParam 的本地化字符串。
        /// </summary>
        internal static string PowerParam {
            get {
                return ResourceManager.GetString("PowerParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerPV 的本地化字符串。
        /// </summary>
        internal static string PowerPV {
            get {
                return ResourceManager.GetString("PowerPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerUpLimit 的本地化字符串。
        /// </summary>
        internal static string PowerUpLimit {
            get {
                return ResourceManager.GetString("PowerUpLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductAddinPara 的本地化字符串。
        /// </summary>
        internal static string ProductAddinPara {
            get {
                return ResourceManager.GetString("ProductAddinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInfo_CapacityOfStatistical 的本地化字符串。
        /// </summary>
        internal static string ProductionInfo_CapacityOfStatistical {
            get {
                return ResourceManager.GetString("ProductionInfo_CapacityOfStatistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInfo_NGNum 的本地化字符串。
        /// </summary>
        internal static string ProductionInfo_NGNum {
            get {
                return ResourceManager.GetString("ProductionInfo_NGNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInfo_OKNum 的本地化字符串。
        /// </summary>
        internal static string ProductionInfo_OKNum {
            get {
                return ResourceManager.GetString("ProductionInfo_OKNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInfo_TotalNum 的本地化字符串。
        /// </summary>
        internal static string ProductionInfo_TotalNum {
            get {
                return ResourceManager.GetString("ProductionInfo_TotalNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInfo_Yield 的本地化字符串。
        /// </summary>
        internal static string ProductionInfo_Yield {
            get {
                return ResourceManager.GetString("ProductionInfo_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductName 的本地化字符串。
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductPara 的本地化字符串。
        /// </summary>
        internal static string ProductPara {
            get {
                return ResourceManager.GetString("ProductPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_Close 的本地化字符串。
        /// </summary>
        internal static string Project_Close {
            get {
                return ResourceManager.GetString("Project_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_Config 的本地化字符串。
        /// </summary>
        internal static string Project_Config {
            get {
                return ResourceManager.GetString("Project_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_New 的本地化字符串。
        /// </summary>
        internal static string Project_New {
            get {
                return ResourceManager.GetString("Project_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_Open 的本地化字符串。
        /// </summary>
        internal static string Project_Open {
            get {
                return ResourceManager.GetString("Project_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_Save 的本地化字符串。
        /// </summary>
        internal static string Project_Save {
            get {
                return ResourceManager.GetString("Project_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project_SaveAs 的本地化字符串。
        /// </summary>
        internal static string Project_SaveAs {
            get {
                return ResourceManager.GetString("Project_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectInfoSet 的本地化字符串。
        /// </summary>
        internal static string ProjectInfoSet {
            get {
                return ResourceManager.GetString("ProjectInfoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickMode 的本地化字符串。
        /// </summary>
        internal static string QuickMode {
            get {
                return ResourceManager.GetString("QuickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuitSystem 的本地化字符串。
        /// </summary>
        internal static string QuitSystem {
            get {
                return ResourceManager.GetString("QuitSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rack 的本地化字符串。
        /// </summary>
        internal static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recieve 的本地化字符串。
        /// </summary>
        internal static string Recieve {
            get {
                return ResourceManager.GetString("Recieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipe 的本地化字符串。
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RedLight 的本地化字符串。
        /// </summary>
        internal static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemoveAll 的本地化字符串。
        /// </summary>
        internal static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReportQuery 的本地化字符串。
        /// </summary>
        internal static string ReportQuery {
            get {
                return ResourceManager.GetString("ReportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result_NG 的本地化字符串。
        /// </summary>
        internal static string Result_NG {
            get {
                return ResourceManager.GetString("Result_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result_OK 的本地化字符串。
        /// </summary>
        internal static string Result_OK {
            get {
                return ResourceManager.GetString("Result_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI 的本地化字符串。
        /// </summary>
        internal static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROIName 的本地化字符串。
        /// </summary>
        internal static string ROIName {
            get {
                return ResourceManager.GetString("ROIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROITpye 的本地化字符串。
        /// </summary>
        internal static string ROIType {
            get {
                return ResourceManager.GetString("ROIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunAuto 的本地化字符串。
        /// </summary>
        internal static string RunAuto {
            get {
                return ResourceManager.GetString("RunAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunCycle 的本地化字符串。
        /// </summary>
        internal static string RunCycle {
            get {
                return ResourceManager.GetString("RunCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunOnce 的本地化字符串。
        /// </summary>
        internal static string RunOnce {
            get {
                return ResourceManager.GetString("RunOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveFile 的本地化字符串。
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveImage 的本地化字符串。
        /// </summary>
        internal static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveProject 的本地化字符串。
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenCapture 的本地化字符串。
        /// </summary>
        internal static string ScreenCapture {
            get {
                return ResourceManager.GetString("ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SearchHelp 的本地化字符串。
        /// </summary>
        internal static string SearchHelp {
            get {
                return ResourceManager.GetString("SearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial 的本地化字符串。
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial 的本地化字符串。
        /// </summary>
        internal static string Serial1 {
            get {
                return ResourceManager.GetString("Serial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serialize 的本地化字符串。
        /// </summary>
        internal static string Serialize {
            get {
                return ResourceManager.GetString("Serialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServoDebug 的本地化字符串。
        /// </summary>
        internal static string ServoDebug {
            get {
                return ResourceManager.GetString("ServoDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set 的本地化字符串。
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siemens7 的本地化字符串。
        /// </summary>
        internal static string Siemens7 {
            get {
                return ResourceManager.GetString("Siemens7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siemens7 的本地化字符串。
        /// </summary>
        internal static string Siemens71 {
            get {
                return ResourceManager.GetString("Siemens71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot 的本地化字符串。
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SN 的本地化字符串。
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoftwareIsExiting 的本地化字符串。
        /// </summary>
        internal static string SoftwareIsExiting {
            get {
                return ResourceManager.GetString("SoftwareIsExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoftwareStartupSucceeded 的本地化字符串。
        /// </summary>
        internal static string SoftwareStartupSucceeded {
            get {
                return ResourceManager.GetString("SoftwareStartupSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoluctionAutoLoad 的本地化字符串。
        /// </summary>
        internal static string SoluctionAutoLoad {
            get {
                return ResourceManager.GetString("SoluctionAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoluctionAutoRun 的本地化字符串。
        /// </summary>
        internal static string SoluctionAutoRun {
            get {
                return ResourceManager.GetString("SoluctionAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoluctionPath 的本地化字符串。
        /// </summary>
        internal static string SoluctionPath {
            get {
                return ResourceManager.GetString("SoluctionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SolutionList 的本地化字符串。
        /// </summary>
        internal static string SolutionList {
            get {
                return ResourceManager.GetString("SolutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartupSetting 的本地化字符串。
        /// </summary>
        internal static string StartupSetting {
            get {
                return ResourceManager.GetString("StartupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopBits 的本地化字符串。
        /// </summary>
        internal static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System_Setting 的本地化字符串。
        /// </summary>
        internal static string System_Setting {
            get {
                return ResourceManager.GetString("System_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemConfig 的本地化字符串。
        /// </summary>
        internal static string SystemConfig {
            get {
                return ResourceManager.GetString("SystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_AutoLoadLayout 的本地化字符串。
        /// </summary>
        internal static string SystemParam_AutoLoadLayout {
            get {
                return ResourceManager.GetString("SystemParam_AutoLoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_Basis 的本地化字符串。
        /// </summary>
        internal static string SystemParam_Basis {
            get {
                return ResourceManager.GetString("SystemParam_Basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_CompanyName 的本地化字符串。
        /// </summary>
        internal static string SystemParam_CompanyName {
            get {
                return ResourceManager.GetString("SystemParam_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_Language 的本地化字符串。
        /// </summary>
        internal static string SystemParam_Language {
            get {
                return ResourceManager.GetString("SystemParam_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_Path 的本地化字符串。
        /// </summary>
        internal static string SystemParam_Path {
            get {
                return ResourceManager.GetString("SystemParam_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_ProjectName 的本地化字符串。
        /// </summary>
        internal static string SystemParam_ProjectName {
            get {
                return ResourceManager.GetString("SystemParam_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_SoftwareIcon 的本地化字符串。
        /// </summary>
        internal static string SystemParam_SoftwareIcon {
            get {
                return ResourceManager.GetString("SystemParam_SoftwareIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_SoftwareSelfStarting 的本地化字符串。
        /// </summary>
        internal static string SystemParam_SoftwareSelfStarting {
            get {
                return ResourceManager.GetString("SystemParam_SoftwareSelfStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_SoftwareVersion 的本地化字符串。
        /// </summary>
        internal static string SystemParam_SoftwareVersion {
            get {
                return ResourceManager.GetString("SystemParam_SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemParam_SystemParam 的本地化字符串。
        /// </summary>
        internal static string SystemParam_SystemParam {
            get {
                return ResourceManager.GetString("SystemParam_SystemParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerMode 的本地化字符串。
        /// </summary>
        internal static string TriggerMode {
            get {
                return ResourceManager.GetString("TriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerSet 的本地化字符串。
        /// </summary>
        internal static string TriggerSet {
            get {
                return ResourceManager.GetString("TriggerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerSource 的本地化字符串。
        /// </summary>
        internal static string TriggerSource {
            get {
                return ResourceManager.GetString("TriggerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIDesign 的本地化字符串。
        /// </summary>
        internal static string UIDesign {
            get {
                return ResourceManager.GetString("UIDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload 的本地化字符串。
        /// </summary>
        internal static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserLogin 的本地化字符串。
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View_Multi 的本地化字符串。
        /// </summary>
        internal static string View_Multi {
            get {
                return ResourceManager.GetString("View_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View_ScreenShot 的本地化字符串。
        /// </summary>
        internal static string View_ScreenShot {
            get {
                return ResourceManager.GetString("View_ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View_Single 的本地化字符串。
        /// </summary>
        internal static string View_Single {
            get {
                return ResourceManager.GetString("View_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View_Theme 的本地化字符串。
        /// </summary>
        internal static string View_Theme {
            get {
                return ResourceManager.GetString("View_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn 的本地化字符串。
        /// </summary>
        internal static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write 的本地化字符串。
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
